# -*- cmake -*-
# Grok (GrokImageCompression/grok) JPEG 2000 codec.
#
# This targets a locally built Grok tree rather than an autobuild "3p"
# prebuilt package, since Grok is licensed under the GNU Affero General
# Public License version 3 and is only safe to bundle into a build that
# does not also link Kakadu, FMOD, or Vivox in the same binary. Anyone
# wiring this in for a distributed build should confirm that condition
# still holds before enabling USE_GROK.
#
# GROK_ROOT should point at a checkout of GrokImageCompression/grok that
# has already been configured and built (see build/bin/grokj2k.lib and
# build/bin/grokj2k.dll). Override with -DGROK_ROOT=... if your checkout
# lives somewhere other than the default below.
#
# Mirrors the structure of LLKDU.cmake: the option, include guard, and
# ll::grok target all exist unconditionally so USE_GROK is a normal,
# always-available CMake option, with only the actual library lookup
# gated on USE_GROK being enabled.

option(USE_GROK "Use Grok (GrokImageCompression/grok) as the Kakadu-free J2C decoder" OFF)

include_guard()
add_library(ll::grok INTERFACE IMPORTED)

if (NOT USE_KDU AND USE_GROK)

set(GROK_ROOT "C:/fs/grok" CACHE PATH "Path to a built GrokImageCompression/grok checkout")

find_library(GROK_LIBRARY
    NAMES
    grokj2k
    PATHS "${GROK_ROOT}/build/bin"
    REQUIRED
    NO_DEFAULT_PATH)

find_file(GROK_RUNTIME_DLL
    NAMES
    grokj2k.dll
    PATHS "${GROK_ROOT}/build/bin"
    NO_DEFAULT_PATH)

target_link_libraries(ll::grok INTERFACE ${GROK_LIBRARY})

# grok.h lives under src/lib/core in the source tree; grk_config.h is
# generated by CMake into the matching path under the build tree, so
# both directories are required on the include path.
target_include_directories(ll::grok SYSTEM INTERFACE
    "${GROK_ROOT}/src/lib/core"
    "${GROK_ROOT}/build/src/lib/core")

if (NOT GROK_RUNTIME_DLL)
    message(WARNING "Grok: could not find grokj2k.dll under ${GROK_ROOT}/build/bin; "
                     "the viewer will fail to start unless it is copied in manually.")
endif ()

endif ()
